# This workflow is to deploy the master branch to the gh-pages branch on changes

name: CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    #Set the node-js version
    strategy:
      matrix:
        node-version: [10.x]
        
    name: Deploy master to gh-pages with Node.js ${{ matrix.node-version }} 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Set up Node.js ${{ matrix.node-version}}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      
#      - name: Cache dependencies
#        uses: actions/cache@v2
#        with:
#          path: |
#            **/node_modules
#          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
#
#      
#      - name: Install dependencies
#        run: npm install
#
#      - name: Deploy to gh-pages
#        run: |
#          git config --global user.name $user_name
#          git config --global user.email $user_email
#          git remote set-url origin https://${github_token}@github.com/${repository}
#          npm run deploy
#        env:
#          user_name: 'github-actions[bot]'
#          user_email: 'github-actions[bot]@users.noreply.github.com'
#          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#          repository: ${{ github.repository }}



